### ISSUE TITLE
Table name when attaching a directory

### ISSUE THREAD

**Issue by romulogoncalves** [MonetDBSolutions/data-vaults#18] opened 2016-09-29 15:22 UTC
call lidarattach('/scratch/goncalve/data/geo_data/ahn3/tileslaz/tests1/');
Leads to 
Initial table name: /scratch/goncalve/data/geo_data/ahn3/tileslaz/tests1/

\d reports
TABLE  sys.

select min(x) from tests1;
leads to
ERROR = !SELECT: no such table 'tests1'

**Comment by kutsurak** [comment] 2016-10-05 14:45
The problem is the following:

The path parsing assumes that it will be attaching a file (my bad sorry), and so it searches for the last directory separator in the string, and ignores everything before it.

As a workaround until this is fixed, you can provide a table name as a second argument: 

call lidarattach('/scratch/goncalve/data/geo_data/ahn3/tileslaz/tests1/', 'tbl0');

**Comment by kutsurak** [comment] 2016-10-05 15:30
Fixed in b5c080c41cdf

**Closed by kutsurak** 2016-10-05 15:30 UTC
Labels: bug
